//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PertinaxInkom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class ADOConnection : global::System.Configuration.ApplicationSettingsBase {
        
        private static ADOConnection defaultInstance = ((ADOConnection)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ADOConnection())));
        
        public static ADOConnection Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.93;uid=pertinaxcheckin;pwd=pertinaxcheckin;database=pertinaxlan")]
        public string Pertinaxlanstr {
            get {
                return ((string)(this["Pertinaxlanstr"]));
            }
        }
    }
}
