//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PertinaxInkom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PertinaxInkom.Properties.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Account.
        /// </summary>
        internal static string C_Account {
            get {
                return ResourceManager.GetString("C_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Address.
        /// </summary>
        internal static string C_Address {
            get {
                return ResourceManager.GetString("C_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_BlockedUuid.
        /// </summary>
        internal static string C_BlockedUuid {
            get {
                return ResourceManager.GetString("C_BlockedUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_UserRole.
        /// </summary>
        internal static string C_UserRole {
            get {
                return ResourceManager.GetString("C_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Wallet.
        /// </summary>
        internal static string C_Wallet {
            get {
                return ResourceManager.GetString("C_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Account.
        /// </summary>
        internal static string D_Account {
            get {
                return ResourceManager.GetString("D_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AccountById.
        /// </summary>
        internal static string S_AccountById {
            get {
                return ResourceManager.GetString("S_AccountById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AccountByName.
        /// </summary>
        internal static string S_AccountByName {
            get {
                return ResourceManager.GetString("S_AccountByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AccountByUsername.
        /// </summary>
        internal static string S_AccountByUsername {
            get {
                return ResourceManager.GetString("S_AccountByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AccountByUUID.
        /// </summary>
        internal static string S_AccountByUUID {
            get {
                return ResourceManager.GetString("S_AccountByUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Accounts.
        /// </summary>
        internal static string S_Accounts {
            get {
                return ResourceManager.GetString("S_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Address.
        /// </summary>
        internal static string S_Address {
            get {
                return ResourceManager.GetString("S_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_AddressByFullAddress.
        /// </summary>
        internal static string S_AddressByFullAddress {
            get {
                return ResourceManager.GetString("S_AddressByFullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_BlockedUuidByUuid.
        /// </summary>
        internal static string S_BlockedUuidByUuid {
            get {
                return ResourceManager.GetString("S_BlockedUuidByUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_LatestEditionNumber.
        /// </summary>
        internal static string S_LatestEditionNumber {
            get {
                return ResourceManager.GetString("S_LatestEditionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Roles.
        /// </summary>
        internal static string S_Roles {
            get {
                return ResourceManager.GetString("S_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_RolesById.
        /// </summary>
        internal static string S_RolesById {
            get {
                return ResourceManager.GetString("S_RolesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_RolesByName.
        /// </summary>
        internal static string S_RolesByName {
            get {
                return ResourceManager.GetString("S_RolesByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_TicketByUUID.
        /// </summary>
        internal static string S_TicketByUUID {
            get {
                return ResourceManager.GetString("S_TicketByUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_TicketType.
        /// </summary>
        internal static string S_TicketType {
            get {
                return ResourceManager.GetString("S_TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_UserRolesByUser.
        /// </summary>
        internal static string S_UserRolesByUser {
            get {
                return ResourceManager.GetString("S_UserRolesByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Wallet.
        /// </summary>
        internal static string S_Wallet {
            get {
                return ResourceManager.GetString("S_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Account.
        /// </summary>
        internal static string U_Account {
            get {
                return ResourceManager.GetString("U_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Address.
        /// </summary>
        internal static string U_Address {
            get {
                return ResourceManager.GetString("U_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_UserRole.
        /// </summary>
        internal static string U_UserRole {
            get {
                return ResourceManager.GetString("U_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Wallet.
        /// </summary>
        internal static string U_Wallet {
            get {
                return ResourceManager.GetString("U_Wallet", resourceCulture);
            }
        }
    }
}
