//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PertinaxInkom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class ZebraConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static ZebraConfig defaultInstance = ((ZebraConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ZebraConfig())));
        
        public static ZebraConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.16.7.201")]
        public string IpVisitorPrinter {
            get {
                return ((string)(this["IpVisitorPrinter"]));
            }
            set {
                this["IpVisitorPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.16.7.202")]
        public string IpParticipantPrinter {
            get {
                return ((string)(this["IpParticipantPrinter"]));
            }
            set {
                this["IpParticipantPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.16.7.203")]
        public string IpCrewVolunteerPrinter {
            get {
                return ((string)(this["IpCrewVolunteerPrinter"]));
            }
            set {
                this["IpCrewVolunteerPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int edition {
            get {
                return ((int)(this["edition"]));
            }
            set {
                this["edition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"$@""
^XA
^FO40,2450^BQN,3,10^FDLA,{barcode}^FS
^FO40,1200^BQN,3,10^FDLA,{barcode}^FS
^FO40,1520^XGE:LOGO.GRF,1,1^FS
^FT87,2354^A0B,67,67^FH\^FDPertinax LAN {edition}^FS
^FT241,2354^A0B,42,40^FH\^FD{firstname}^FS
^FT241,2166^A0B,42,40^FH\^FD{lastname}^FS
^FT174,2354^A0B,67,67^FH\^FD{nickname}^FS
^PQ1,0,1,Y
^XZ"";")]
        public string zplcode {
            get {
                return ((string)(this["zplcode"]));
            }
            set {
                this["zplcode"] = value;
            }
        }
    }
}
